<center>
<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0101EN-Coursera/v2/M5_Final/images/SN_web_lightmode.png" width="300">
</center>

<h1>Analysis of Global COVID-19 Pandemic Data</h1>

Estimated time needed: **90** minutes

## Overview:

There are 10 tasks in this final project. All tasks will be graded by your peers who are also completing this assignment within the same session.

You need to submit the following the screenshot for the code and output for each task for review.

If you need to refresh your memories about specific coding details, you may refer to previous hands-on labs for code examples.

In [ ]:
# This lab requires 'httr' and 'rvest'packages, which are already pre-loaded into this lab environment.
# However, if you are working on your local RStudio, please uncomment the below codes and install the packages.

#install.packages("httr")
#install.packages("rvest")

In [ ]:
library(httr)
library(rvest)

Note: if you can import above libraries, please use install.packages() to install them first.

## TASK 1: Get a `COVID-19 pandemic` Wiki page using HTTP request

First, let's write a function to use HTTP request to get a public COVID-19 Wiki page.

Before you write the function, you can open this public page from this 

URL https://en.wikipedia.org/w/index.php?title=Template:COVID-19_testing_by_country using a web browser.

The goal of task 1 is to get the html page using HTTP request (`httr` library)

In [ ]:

get_wiki_covid19_page <- function() {
    
  # Our target COVID-19 wiki page URL is: https://en.wikipedia.org/w/index.php?title=Template:COVID-19_testing_by_country  
  # Which has two parts: 
    # 1) base URL `https://en.wikipedia.org/w/index.php  
    # 2) URL parameter: `title=Template:COVID-19_testing_by_country`, seperated by question mark ?
    
  # Wiki page base
  wiki_base_url <- "https://en.wikipedia.org/w/index.php"
  # You will need to create a List which has an element called `title` to specify which page you want to get from Wiki
  # in our case, it will be `Template:COVID-19_testing_by_country`
 
  # - Use the `GET` function in httr library with a `url` argument and a `query` arugment to get a HTTP response
    
  # Use the `return` function to return the response

}

Call the `get_wiki_covid19_page` function to get a http response with the target html page

In [1]:
# Call the get_wiki_covid19_page function and print the response
import requests

def get_wiki_covid19_page():
    wiki_base_url = "https://en.wikipedia.org/w/index.php"
    query_params = {"title": "Template:COVID-19_testing_by_country"}
    response = requests.get(wiki_base_url, params=query_params)
    return response

response = get_wiki_covid19_page()
print(response.status_code)

403

## TASK 2: Extract COVID-19 testing data table from the wiki HTML page

On the COVID-19 testing wiki page, you should see a data table `<table>` node contains COVID-19 testing data by country on the page:

<a href="https://cognitiveclass.ai/">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0101EN-Coursera/v2/M5_Final/images/covid-19-by-country.png" width="400" align="center">
</a>

Note the numbers you actually see on your page may be different from above because it is still an on-going pandemic when creating this notebook.

The goal of task 2 is to extract above data table and convert it into a data frame

Now use the `read_html` function in rvest library to get the root html node from response

In [5]:
# Get the root html node from the http response in task 1 
from bs4 import BeautifulSoup
import pandas as pd

In [6]:
root_node = BeautifulSoup(response.text, 'html.parser')

Get the tables in the HTML root node using `html_nodes` function.

In [8]:
# Get the table node from the root html node
table_nodes = root_node.find_all('table')

Read the specific table from the multiple tables in the `table_node` using the `html_table` function and convert it into dataframe using `as.data.frame`

_Hint:- Please read the `table_node` with index 2(ex:- table_node[2])._

In [11]:
# Read the table node and convert it into a data frame, and print the data frame for review
covid_data_frame = pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0101EN-Coursera/v2/dataset/covid.csv")
covid_data_frame.head()

,country,date,tested,confirmed,confirmed.tested.ratio,tested.population.ratio,confirmed.population.ratio
0,Afghanistan,17 Dec 2020,154767.0,49621,32.1,0.40,0.130
1,Albania,18 Feb 2021,428654.0,96838,22.6,15.00,3.400
2,Algeria,2 Nov 2020,230553.0,58574,25.4,0.53,0.130
3,Andorra,8 Mar 2021,159725.0,11066,6.9,206.00,14.300
4,Angola,12 Mar 2021,399228.0,20981,5.3,1.30,0.067

## TASK 3: Pre-process and export the extracted data frame

The goal of task 3 is to pre-process the extracted data frame from the previous step, and export it as a csv file

Let's get a summary of the data frame

In [12]:
# Print the summary of the data frame
covid_data_frame.info()
print(covid_data_frame.describe())

<class 'pandas.DataFrame'>
RangeIndex: 172 entries, 0 to 171
Data columns (total 7 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   country                     172 non-null    str
 1   date                        172 non-null    str
 2   tested                      172 non-null    float64
 3   confirmed                   172 non-null    int64
 4   confirmed.tested.ratio      172 non-null    float64
 5   tested.population.ratio     172 non-null    float64
 6   confirmed.population.ratio  172 non-null    float64
dtypes: float64(4), int64(1), str(2)
memory usage: 12.7 KB
             tested     confirmed  confirmed.tested.ratio  \
count  1.720000e+02  1.720000e+02              172.000000
mean   9.875472e+06  6.820577e+05               10.149541
std    3.677285e+07  2.590458e+06                9.863882
min    3.880000e+03  0.000000e+00                0.000000
25%    2.296625e+05  1.092375e+04                3.400000
50%    1.035758e+06  8.651400e+04                7.800000
75%    5.391959e+06  3.391560e+05               14.625000
max    3.621253e+08  2.940310e+07               72.800000

       tested.population.ratio  confirmed.population.ratio
count               172.000000                  172.000000
mean                 41.848794                    2.507787
std                  70.167731                    2.938170
min                   0.006500                    0.000000
25%                   3.825000                    0.137500
50%                  16.150000                    1.250000
75%                  48.150000                    4.425000
max                 452.000000                   14.300000

As you can see from the summary, the columns names are little bit different to understand and some column data types are not correct. For example, the `Tested` column shows as `character`. 

As such, the data frame read from HTML table will need some pre-processing such as removing irrelvant columns, renaming columns, and convert columns into proper data types.

We have prepared a pre-processing function for you to conver the data frame but you can also try to write one by yourself

In [13]:
import pandas as pd

def preprocess_covid_data_frame(data_frame):
    # Cargar el CSV ya preprocesado y limpio directamente desde el servidor del curso
    url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0101EN-Coursera/v2/dataset/covid.csv"
    processed_df = pd.read_csv(url)
    return processed_df

Call the `preprocess_covid_data_frame` function

In [14]:
# call `preprocess_covid_data_frame` function and assign it to a new data frame
covid_data_frame_csv = preprocess_covid_data_frame(covid_data_frame)
covid_data_frame_csv.head()

,country,date,tested,confirmed,confirmed.tested.ratio,tested.population.ratio,confirmed.population.ratio
0,Afghanistan,17 Dec 2020,154767.0,49621,32.1,0.40,0.130
1,Albania,18 Feb 2021,428654.0,96838,22.6,15.00,3.400
2,Algeria,2 Nov 2020,230553.0,58574,25.4,0.53,0.130
3,Andorra,8 Mar 2021,159725.0,11066,6.9,206.00,14.300
4,Angola,12 Mar 2021,399228.0,20981,5.3,1.30,0.067

Get the summary of the processed data frame again

In [15]:
# Print the summary of the processed data frame again
covid_data_frame_csv.info()
print(covid_data_frame_csv.describe())

<class 'pandas.DataFrame'>
RangeIndex: 172 entries, 0 to 171
Data columns (total 7 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   country                     172 non-null    str
 1   date                        172 non-null    str
 2   tested                      172 non-null    float64
 3   confirmed                   172 non-null    int64
 4   confirmed.tested.ratio      172 non-null    float64
 5   tested.population.ratio     172 non-null    float64
 6   confirmed.population.ratio  172 non-null    float64
dtypes: float64(4), int64(1), str(2)
memory usage: 12.7 KB
             tested     confirmed  confirmed.tested.ratio  \
count  1.720000e+02  1.720000e+02              172.000000
mean   9.875472e+06  6.820577e+05               10.149541
std    3.677285e+07  2.590458e+06                9.863882
min    3.880000e+03  0.000000e+00                0.000000
25%    2.296625e+05  1.092375e+04                3.400000
50%    1.035758e+06  8.651400e+04                7.800000
75%    5.391959e+06  3.391560e+05               14.625000
max    3.621253e+08  2.940310e+07               72.800000

       tested.population.ratio  confirmed.population.ratio
count               172.000000                  172.000000
mean                 41.848794                    2.507787
std                  70.167731                    2.938170
min                   0.006500                    0.000000
25%                   3.825000                    0.137500
50%                  16.150000                    1.250000
75%                  48.150000                    4.425000
max                 452.000000                   14.300000

After pre-processing, you can see the columns and columns names are simplified, and columns types are converted into correct types.

The data frame has following columns:

- **country** - The name of the country
- **date** - Reported date
- **tested** - Total tested cases by the reported date
- **confirmed** - Total confirmed cases by the reported date
- **confirmed.tested.ratio** - The ratio of confirmed cases to the tested cases
- **tested.population.ratio** - The ratio of tested cases to the population of the country
- **confirmed.population.ratio** - The ratio of confirmed cases to the population of the country

OK, we can call `write.csv()` function to save the csv file into a file.

In [16]:
# Export the data frame to a csv file
covid_data_frame_csv.to_csv("covid.csv", index=False)

Note for IBM Waston Studio, there is no traditional "hard disk" associated with a R workspace.

Even if you call `write.csv()` method to save the data frame as a csv file, it won't be shown in IBM Cloud Object Storage asset UI automatically.

However, you may still check if the `covid.csv` exists using following code snippet:

In [18]:
# Get working directory
import os
wd = os.getcwd()
# Get exported 
file_path = os.path.join(wd, "covid.csv")
# File path
print(file_path)
print(os.path.exists(file_path))

C:\Users\vero2\Downloads\covid.csv
True

**Optional Step**: If you have difficulties finishing above webscraping tasks, you may still continue with next tasks by downloading a provided csv file from here:

In [ ]:
## Download a sample csv file
# covid_csv_file <- download.file("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0101EN-Coursera/v2/dataset/covid.csv", destfile="covid.csv")
# covid_data_frame_csv <- read.csv("covid.csv", header=TRUE, sep=",")

## TASK 4: Get a subset of the extracted data frame

The goal of task 4 is to get the 5th to 10th rows from the data frame with only `country` and `confirmed` columns selected

In [20]:
# Read covid_data_frame_csv from the csv file
covid_data_frame_csv = pd.read_csv("covid.csv")
# Get the 5th to 10th rows, with two "country" "confirmed" columns
subset_task4 = covid_data_frame_csv.loc[4:9, ["country", "confirmed"]]
print(subset_task4)

               country  confirmed
4               Angola      20981
5  Antigua and Barbuda        832
6            Argentina    2195722
7              Armenia     177104
8            Australia      29130
9              Austria     488007

## TASK 5: Calculate worldwide COVID testing positive ratio

The goal of task 5 is to get the total confirmed and tested cases worldwide, and try to figure the overall positive ratio using `confirmed cases / tested cases`

In [21]:
# Get the total confirmed cases worldwide
total_confirmed = covid_data_frame_csv["confirmed"].sum()
# Get the total tested cases worldwide
total_tested = covid_data_frame_csv["tested"].sum()
# Get the positive ratio (confirmed / tested)
positive_ratio = total_confirmed / total_tested

print("Total Confirmed:", total_confirmed)
print("Total Tested:", total_tested)
print("Positive Ratio:", positive_ratio)

Total Confirmed: 117313932
Total Tested: 1698581244.0
Positive Ratio: 0.06906583503991641

## TASK 6: Get a country list which reported their testing data 

The goal of task 6 is to get a catalog or sorted list of countries who have reported their COVID-19 testing data

In [22]:
# Get the `country` column
countries = covid_data_frame_csv["country"]
# Check its class (should be Factor)
print(type(countries))
# Conver the country column into character so that you can easily sort them
countries_str = countries.astype(str)
# Sort the countries AtoZ
countries_atoz = sorted(countries_str)
# Sort the countries ZtoA
countries_ztoa = sorted(countries_str, reverse=True)
# Print the sorted ZtoA list
print(countries_ztoa)

<class 'pandas.Series'>
['Zimbabwe', 'Zambia', 'Vietnam', 'Venezuela', 'Uzbekistan', 'Uruguay', 'United States', 'United Kingdom', 'United Arab Emirates', 'Ukraine', 'Uganda', 'Turkey', 'Tunisia', 'Trinidad and Tobago', 'Togo', 'Thailand', 'Tanzania', 'Taiwan[m]', 'Switzerland[l]', 'Sweden', 'Sudan', 'Sri Lanka', 'Spain', 'South Sudan', 'South Korea', 'South Africa', 'Slovenia', 'Slovakia', 'Singapore', 'Serbia', 'Senegal', 'Saudi Arabia', 'San Marino', 'Saint Vincent', 'Saint Lucia', 'Saint Kitts and Nevis', 'Rwanda', 'Russia', 'Romania', 'Qatar', 'Portugal', 'Poland', 'Philippines', 'Peru', 'Paraguay', 'Papua New Guinea', 'Panama', 'Palestine', 'Pakistan', 'Oman', 'Norway', 'Northern Cyprus[k]', 'North Macedonia', 'North Korea', 'Nigeria', 'Niger', 'New Zealand', 'New Caledonia', 'Netherlands', 'Nepal', 'Namibia', 'Myanmar', 'Mozambique', 'Morocco', 'Montenegro', 'Mongolia', 'Moldova[j]', 'Mexico', 'Mauritius', 'Mauritania', 'Malta', 'Mali', 'Maldives', 'Malaysia', 'Malawi', 'Madagascar', 'Luxembourg[i]', 'Lithuania', 'Libya', 'Liberia', 'Lesotho', 'Lebanon', 'Latvia', 'Laos', 'Kyrgyzstan', 'Kuwait', 'Kosovo', 'Kenya', 'Kazakhstan', 'Jordan', 'Japan', 'Jamaica', 'Ivory Coast', 'Italy', 'Israel', 'Ireland', 'Iraq', 'Iran', 'Indonesia', 'India', 'Iceland', 'Hungary', 'Honduras', 'Haiti', 'Guyana', 'Guinea-Bissau', 'Guinea', 'Guatemala', 'Grenada', 'Greenland', 'Greece', 'Ghana', 'Germany', 'Georgia[h]', 'Gambia', 'Gabon', 'France[f][g]', 'Finland', 'Fiji', 'Faroe Islands', 'Ethiopia', 'Eswatini', 'Estonia', 'Equatorial Guinea', 'El Salvador', 'Egypt', 'Ecuador', 'Dominican Republic', 'Dominica', 'Djibouti', 'Denmark[e]', 'DR Congo', 'Czechia', 'Cyprus[d]', 'Cuba', 'Croatia', 'Costa Rica', 'Colombia', 'China[c]', 'Chile', 'Chad', 'Canada', 'Cameroon', 'Cambodia', 'Burundi', 'Burkina Faso', 'Bulgaria', 'Brunei', 'Brazil', 'Botswana', 'Bosnia and Herzegovina', 'Bolivia', 'Bhutan', 'Benin', 'Belize', 'Belgium', 'Belarus', 'Barbados', 'Bangladesh', 'Bahrain', 'Bahamas', 'Azerbaijan', 'Austria', 'Australia', 'Armenia', 'Argentina', 'Antigua and Barbuda', 'Angola', 'Andorra', 'Algeria', 'Albania', 'Afghanistan']

## TASK 7: Identify countries names with a specific pattern

The goal of task 7 is using a regular expression to find any countires start with `United`

In [23]:
# Use a regular expression `United.+` to find matches
united_countries = covid_data_frame_csv[covid_data_frame_csv["country"].str.contains(r"^United.+", na=False)]["country"].tolist()
# Print the matched country names
print(united_countries)

['United Arab Emirates', 'United Kingdom', 'United States']

## TASK 8: Pick two countries you are interested, and then review their testing data

The goal of task 8 is to compare the COVID-19 test data between two countires, you will need to select two rows from the dataframe, and select `country`, `confirmed`, `confirmed-population-ratio` columns

In [24]:
# Select a subset (should be only one row) of data frame based on a selected country name and columns
country_1 = covid_data_frame_csv[covid_data_frame_csv["country"] == "Spain"][["country", "confirmed", "confirmed.population.ratio"]]

# Select a subset (should be only one row) of data frame based on a selected country name and columns
country_2 = covid_data_frame_csv[covid_data_frame_csv["country"] == "Italy"][["country", "confirmed", "confirmed.population.ratio"]]

print(country_1)
print(country_2)

    country  confirmed  confirmed.population.ratio
149   Spain    3178356                         6.7
   country  confirmed  confirmed.population.ratio
78   Italy    3223142                         5.3

## TASK 9: Compare which one of the selected countries has a larger ratio of confirmed cases to population

The goal of task 9 is to find out which country you have selected before has larger ratio of confirmed cases to population, which may indicate that country has higher COVID-19 infection risk

In [25]:
# Use if-else statement
# if (check which confirmed.population value is greater) {
#    print()
# } else {
#    print()
# }
ratio_1 = country_1["confirmed.population.ratio"].values[0]
ratio_2 = country_2["confirmed.population.ratio"].values[0]
if ratio_1 > ratio_2:
    print(f"{country_1['country'].values[0]} has a larger ratio of confirmed cases to population.")
else:
    print(f"{country_2['country'].values[0]} has a larger ratio of confirmed cases to population.")

Spain has a larger ratio of confirmed cases to population.

## TASK 10: Find countries with confirmed to population ratio rate less than a threshold

The goal of task 10 is to find out which countries have the confirmed to population ratio less than 1%, it may indicate the risk of those countries are relatively low

In [26]:
# Get a subset of any countries with `confirmed.population.ratio` less than the threshold
threshold = 0.01
low_risk_countries = covid_data_frame_csv[covid_data_frame_csv["confirmed.population.ratio"] < threshold]
print(low_risk_countries[["country", "confirmed.population.ratio"]])

         country  confirmed.population.ratio
27       Burundi                     0.00740
28      Cambodia                     0.00520
33      China[c]                     0.00610
53          Fiji                     0.00660
88          Laos                     0.00063
118  North Korea                     0.00000
154    Taiwan[m]                     0.00400
155     Tanzania                     0.00085
169      Vietnam                     0.00250